USE MESTRE_DAS_FACAS;

-- tabela gênero
INSERT INTO GENERO (DESCRICAO_GENERO) VALUES ('FEMININO');
INSERT INTO GENERO (DESCRICAO_GENERO) VALUES ('MASCULINO');
INSERT INTO GENERO (DESCRICAO_GENERO) VALUES ('NÃO-BINÁRIO');
INSERT INTO GENERO (DESCRICAO_GENERO) VALUES ('OUTROS');

-- tabela uf
INSERT INTO UF VALUES ('AC', 'ACRE');
INSERT INTO UF VALUES ('AL', 'ALAGOAS');
INSERT INTO UF VALUES ('AM', 'AMAZONAS');
INSERT INTO UF VALUES ('AP', 'AMAPÁ');
INSERT INTO UF VALUES ('BA', 'BAHIA');
INSERT INTO UF VALUES ('CE', 'CEARÁ');
INSERT INTO UF VALUES ('DF', 'DISTRITO FEDERAL');
INSERT INTO UF VALUES ('ES', 'ESPÍRITO SANTO');
INSERT INTO UF VALUES ('GO', 'GOIÁS');
INSERT INTO UF VALUES ('MA', 'MARANHÃO');
INSERT INTO UF VALUES ('MG', 'MINAS GERAIS');
INSERT INTO UF VALUES ('MS', 'MATO GROSSO DO SUL');
INSERT INTO UF VALUES ('MT', 'MATO GROSSO');
INSERT INTO UF VALUES ('PA', 'PARÁ');
INSERT INTO UF VALUES ('PB', 'PARAÍBA');
INSERT INTO UF VALUES ('PE', 'PERNAMBUCO');
INSERT INTO UF VALUES ('PI', 'PIAUÍ');
INSERT INTO UF VALUES ('PR', 'PARANÁ');
INSERT INTO UF VALUES ('RJ', 'RIO DE JANEIRO');
INSERT INTO UF VALUES ('RN', 'RIO GRANDE DO NORTE');
INSERT INTO UF VALUES ('RO', 'RONDÔNIA');
INSERT INTO UF VALUES ('RR', 'RORAIMA');
INSERT INTO UF VALUES ('RS', 'RIO GRANDE DO SUL');
INSERT INTO UF VALUES ('SC', 'SANTA CATARINA');
INSERT INTO UF VALUES ('SE', 'SERGIPE');
INSERT INTO UF VALUES ('SP', 'SÃO PAULO');
INSERT INTO UF VALUES ('TO', 'TOCANTINS');

-- tabela bandeira cartao
INSERT INTO BANDEIRA (DESCRICAO_BANDEIRA) VALUES ('VISA');
INSERT INTO BANDEIRA (DESCRICAO_BANDEIRA) VALUES ('MASTERCARD');
INSERT INTO BANDEIRA (DESCRICAO_BANDEIRA) VALUES ('ELO');
INSERT INTO BANDEIRA (DESCRICAO_BANDEIRA) VALUES ('HIPERCARD');
INSERT INTO BANDEIRA (DESCRICAO_BANDEIRA) VALUES ('AMERICAN EXPRESS');
INSERT INTO BANDEIRA (DESCRICAO_BANDEIRA) VALUES ('DINERS CLUB');
